name: Deploy to VPS

on:
  push:
    branches:
      - main # Nur für Pushes in den "main"-Branch ausführen

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 193.22.146.48 >> ~/.ssh/known_hosts

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -t webadmin@193.22.146.48 "bash -l -c 'source ~/.nvm/nvm.sh && nvm use 22.11.0 && cd ../../../var/www/nextjs/CliffEleVen-Sport-Mangement && git pull origin main && npm install && npm run build && pm2 stop 0 && pm2 start npm --name \"cliffeleven\" -- start && pm2 save'"
        env:
          SSH_AUTH_SOCK: /tmp/ssh-XXXXXX8liWr6/agent.1828 # Sicherstellen, dass die SSH-Umgebung korrekt gesetzt ist
